name: Monthly ETL Job

on:
  schedule:
    - cron: '0 0 1 * *'

permissions:
  contents: read

jobs:
  run_etl:
    runs-on: ubuntu-latest

    steps:

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # ratchet:aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::053932140667:role/mongulu-github
      #     role-session-name: tchoungte-deployment
      #     aws-region: eu-central-1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt

      - name: Download and unzip RNA WALDEC
        run: |
          echo "Searching for latest rna waldec version"
          python -c "
          import etl.update_database as ud
          path = ud.search_and_download_data()
          print(f'Extracted file: {path}')
          folder = ud.unzip_and_delete(path)
          import os
          os.remove(path)
          print('Deleted zip file')
          with open('rna_folder.txt', 'w') as f:
              f.write(folder)
          "

      - name: Run filter-cameroon.py
        run: |
          folder=$(cat rna_folder.txt)
          npm install -g secretsfoundry
          cd etl/
          secretsfoundry run --script "python filter-cameroon.py --rna_folder $folder"

      - name: Run enrich-database.py
        run: |
          cd etl/
          secretsfoundry run --script "python enrich-database.py --rna_file rna-real-mars-2022-new.csv"