name: Monthly ETL Job

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month

jobs:
  run_etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt

      - name: Run update_database.py
        run: python etl/update_database.py